# Generated by Django 6.0.5 on 2026-05-27 08:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma")], max_length=20, verbose_name="To'lov usuli")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('paid', "To'landi"), ('failed', 'Muvaffaqiyatsiz'), ('refunded', 'Qaytarildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Summa')),
                ('currency', models.CharField(default='UZS', max_length=10, verbose_name='Valyuta')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Tranzaksiya ID')),
                ('provider', models.CharField(blank=True, max_length=100, verbose_name="To'lov tizimi")),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="To'langan vaqti")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Buyurtma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
