# Generated by Django 6.0.5 on 2026-05-26 08:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil rasmi')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlanganmi')),
                ('role', models.CharField(choices=[('customer', 'Mijoz'), ('seller', 'Sotuvchi'), ('admin', 'Admin')], default='customer', max_length=10, verbose_name='Rol')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Bloklangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Kirish'), ('logout', 'Chiqish'), ('password_change', "Parol o'zgartirish"), ('profile_update', 'Profil yangilash'), ('register', "Ro'yxatdan o'tish")], max_length=20, verbose_name='Harakat')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faollik tarixi',
                'verbose_name_plural': 'Faollik tarixlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Kod')),
                ('purpose', models.CharField(choices=[('register', "Ro'yxatdan o'tish"), ('reset', 'Parolni tiklash')], default='register', max_length=10, verbose_name='Maqsad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False, verbose_name='Ishlatildi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tasdiqlash kodi',
                'verbose_name_plural': 'Tasdiqlash kodlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
