# Generated by Django 6.0.5 on 2026-05-27 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('notification_type', models.CharField(choices=[('system', 'Tizim'), ('order', 'Buyurtma'), ('payment', "To'lov"), ('promotion', 'Aksiya')], default='system', max_length=20, verbose_name='Turi')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qildi")),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan vaqti")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_updates', models.BooleanField(default=True, verbose_name='Buyurtma yangilanishlari')),
                ('payment_updates', models.BooleanField(default=True, verbose_name="To'lov yangilanishlari")),
                ('promotions', models.BooleanField(default=True, verbose_name='Aksiyalar')),
                ('system_updates', models.BooleanField(default=True, verbose_name='Tizim xabarlari')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma sozlamalari',
                'verbose_name_plural': 'Bildirishnoma sozlamalari',
            },
        ),
    ]
